repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        -   id: check-toml
        -   id: debug-statements
        -   id: detect-private-key
  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.29.1
      hooks:
        -   id: pyupgrade
            args: [--py36-plus]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear,flake8-print]

  -   repo: https://github.com/psf/black
      rev: 21.11b1
      hooks:
        -   id: black
