# Generated by Django 3.1.13 on 2021-12-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenue',
            options={'verbose_name': 'Revenue', 'verbose_name_plural': 'Revenues'},
        ),
        migrations.AlterModelTable(
            name='revenue',
            table='Revenues',
        ),
    ]
