# Generated by Django 3.1.14 on 2022-02-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='item',
            field=models.CharField(default='', max_length=250),
        ),
    ]
