# Generated by Django 3.1.14 on 2022-02-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='item',
            field=models.CharField(max_length=250, verbose_name='Item'),
        ),
    ]
