# Generated by Django 3.1.14 on 2022-03-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20220225_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
    ]
