# Generated by Django 3.1.14 on 2022-06-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220307_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='extra_args',
            field=models.JSONField(default=dict, verbose_name='Extra Arguments', blank=True),
        ),
    ]
